### PR TITLE
chore(relayer): simplify setInitialIndexingBlockByMode function

### PR DESCRIPTION
**Pull request by mask-pp**

### CODE REVIEW

**Review by xiaodino — APPROVED** [review]

**Comment by cyberhorsey** [comment]
this PR breaks the relayer as the initial boot up no longer gets the genesis clock from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet.

**Comment by mask-pp** [comment]
> this PR breaks the relayer as the initial boot up no longer gets the genesis block from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet on initial bootup when used in regular Sync mode.
> 
> Do not merge.
> 
> @xiaodino this PR should not be approved.

The func aims to change latestIndexedBlockNumber, 
the logic is:
if mode == Sync:
    change latestIndexedBlockNumber 
if mode == Resync:
    change  latestIndexedBlockNumber
else
    return err

Is that so?

**Comment by cyberhorsey** [comment]
> > this PR breaks the relayer as the initial boot up no longer gets the genesis block from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet on initial bootup when used in regular Sync mode.
> > Do not merge.
> > @xiaodino this PR should not be approved.
> 
> The func aims to change latestIndexedBlockNumber, the logic is: if mode == Sync: change latestIndexedBlockNumber if mode == Resync: change latestIndexedBlockNumber else return err
> 
> Is that so? I saw that this function can be understood in this way

Why are you trying to change this function? It is small and works as intended.

**Comment by mask-pp** [comment]
> > > this PR breaks the relayer as the initial boot up no longer gets the genesis block from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet on initial bootup when used in regular Sync mode.
> > > Do not merge.
> > > @xiaodino this PR should not be approved.
> > 
> > 
> > The func aims to change latestIndexedBlockNumber, the logic is: if mode == Sync: change latestIndexedBlockNumber if mode == Resync: change latestIndexedBlockNumber else return err
> > Is that so? I saw that this function can be understood in this way
> 
> Why are you trying to change this function? It is small and works as intended. There is quite a lot of work to be done that isn't refactoring 15 line functions for no reason, that work as intended? I outlined how this PR breaks the intended functionality above.
> 
> You should be able to see the difference between your code, and the original function.
> 
> If the mode is Sync, we will no longer use the state variables from taiko L1 anymore, whereas before, we do. Right?



> > > this PR breaks the relayer as the initial boot up no longer gets the genesis block from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet on initial bootup when used in regular Sync mode.
> > > Do not merge.
> > > @xiaodino this PR should not be approved.
> > 
> > 
> > The func aims to change latestIndexedBlockNumber, the logic is: if mode == Sync: change latestIndexedBlockNumber if mode == Resync: change latestIndexedBlockNumber else return err
> > Is that so? I saw that this function can be understood in this way
> 
> Why are you trying to change this function? It is small and works as intended. There is quite a lot of work to be done that isn't refactoring 15 line functions for no reason, that work as intended? I outlined how this PR breaks the intended functionality above.
> 
> You should be able to see the difference between your code, and the original function.
> 
> If the mode is Sync, we will no longer use the state variables from taiko L1 anymore, whereas before, we do. Right?

Understand. This is indeed a small and indispensable change. This is a PR I mentioned while browsing realyer.

**Comment by cyberhorsey** [comment]
> > > > this PR breaks the relayer as the initial boot up no longer gets the genesis block from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet on initial bootup when used in regular Sync mode.
> > > > Do not merge.
> > > > @xiaodino this PR should not be approved.
> > > 
> > > 
> > > The func aims to change latestIndexedBlockNumber, the logic is: if mode == Sync: change latestIndexedBlockNumber if mode == Resync: change latestIndexedBlockNumber else return err
> > > Is that so? I saw that this function can be understood in this way
> > 
> > 
> > Why are you trying to change this function? It is small and works as intended. There is quite a lot of work to be done that isn't refactoring 15 line functions for no reason, that work as intended? I outlined how this PR breaks the intended functionality above.
> > You should be able to see the difference between your code, and the original function.
> > If the mode is Sync, we will no longer use the state variables from taiko L1 anymore, whereas before, we do. Right?
> 
> > > > this PR breaks the relayer as the initial boot up no longer gets the genesis block from the taikoL1 contract in sync mode, and always starts from block 0 now on Ethereum mainnet on initial bootup when used in regular Sync mode.
> > > > Do not merge.
> > > > @xiaodino this PR should not be approved.
> > > 
> > > 
> > > The func aims to change latestIndexedBlockNumber, the logic is: if mode == Sync: change latestIndexedBlockNumber if mode == Resync: change latestIndexedBlockNumber else return err
> > > Is that so? I saw that this function can be understood in this way
> > 
> > 
> > Why are you trying to change this function? It is small and works as intended. There is quite a lot of work to be done that isn't refactoring 15 line functions for no reason, that work as intended? I outlined how this PR breaks the intended functionality above.
> > You should be able to see the difference between your code, and the original function.
> > If the mode is Sync, we will no longer use the state variables from taiko L1 anymore, whereas before, we do. Right?
> 
> Understand. This is indeed a small and indispensable change. This is a PR I mentioned while browsing realyer.

@xiaodino please be more careful reviewing PRs please. This would have broken the relayer.

**Pull request closed without merging**
