### PR TITLE
fix(website): Added description and article link　#13869

### LINKED ISSUE #13869: feat(docs): provide info about prover/proposer simple tokenomics
### Describe the feature request

Provide some info about the tokenomics for the provers
 -  have eth on L1 and receive TKO(?) for blocks proved on L1

and proposers:
 - have eth on L1 and receive eth on L2
 - info about that we can change the L2_SUGGESTED_FEE_RECIPIENT for proposers 

Just some quick and easy to understand tokenomics for the node types would be useful so people know how to prepare and how it works

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

### PR DESCRIPTION
**Pull request by nollie0107**
Understanding taiko's proof scheme is very important to increase the probability of success of prover/proposer.
The team has previously mentioned an article explaining the l3 slash, but since it is not mentioned in the doc, i have included it here for the benefit of future learners.

### CODE REVIEW

**Comment by nollie0107** [comment]
I wanted to link to issue #13869 but could not.

**Comment by nollie0107** [comment]
@davidtaikocha thanks suport!

**Comment by dantaik** [comment]
The next testnet is coming soon, with a different fee-model design. The previous info has been deprecated. But thank you for helping out, I appreciate it.

**Comment by nollie0107** [comment]
You're welcome!
I look forward to the next testnet!

**Pull request closed without merging**
