### PR TITLE
fix(bridge-ui): correct display of forward arrow and handling of invalid pagination input

### LINKED ISSUE #16468: Pagination Bug: Negative Page Input Displays a Trucated Data on the Transaction Page
### Describe the bug

When inputting a negative page number (-1) in the page input field on the transaction page, the pagination feature truncates the display to only the first two rows on page one, and does not handle the negative input appropriately.

### Steps to reproduce

1. Navigate to the transaction records page: https://bridge.katla.taiko.xyz/transactions.
2. Input "-1" into the page input field.
3. Press the "Go" or "Submit" button to navigate to the specified page.

**Expected Behavior:**
The pagination system should handle negative page inputs gracefully, either by displaying an error message indicating that negative page numbers are not allowed, or by maintaining the current page without any changes.

**Actual Behavior:**
After inputting "-1" and submitting, only the first two rows of page one are displayed, while the rest of the records are truncated, leading to incomplete data presentation.

**Additional Information:**
Browser/Environment: Chrome Version 122.0.6261.129 
Operating System: Windows 11

Taiko-transaction log page-1
Taiko-transaction log page-2

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

### PR DESCRIPTION
**Pull request by courage-ugwuanyi**
**This pull request addresses:**
1.  A bug related to pagination in the transactions page. Previously, the forward arrow button was incorrectly displayed even beyond the last page, leading to confusion for users. This bug has been fixed to ensure that the forward arrow button is displayed only when there are additional pages to navigate to.

2. Previously, when users input a number greater than the total number of pages in the pagination input field, the application would attempt to navigate to the specified page, leading to unexpected behaviour. This commit addresses this issue by adding validation in the handleKeydown function to check if the input number exceeds the total number of pages. If the input is invalid, the application ignores the input and does nothing.

**Changes:**
- Modified the pagination logic to accurately determine when to display the forward arrow button.
- Added validation in the handleKeydown function to handle input of a number greater than the total number of pages.
- Implemented a mechanism to ignore invalid input, ensuring consistent and expected behaviour in the pagination component.

**How to Test:**
1. Navigate to the transaction records page: https://bridge.katla.taiko.xyz/transactions 
2. Verify that the forward arrow button is not displayed on the last page.
3. Verify that nothing happens if a number greater than the last page number is entered.
4. Input a number greater than the total number of pages and ensure that the forward arrow button remains hidden.

closes #16468

### CODE REVIEW

**Comment by courage-ugwuanyi** [comment]
@KorbinianK, Sorry, I was having so many issues to fix the lint error. So I had to delete the repo and start afresh. Could you please verify if it is now working ? Thanks

**Comment by KorbinianK** [comment]
@courage-ugwuanyi it still fails when linting. Run `pnpm svelte:check && pnpm lint:fix`

**Comment by courage-ugwuanyi** [comment]
> @courage-ugwuanyi it still fails when linting. Run `pnpm svelte:check && pnpm lint:fix` https://github.com/taikoxyz/taiko-mono/pull/16485/files

@KorbinianK Please check if it works now. Thanks

**Review by KorbinianK — APPROVED** [review]

**Review by xiaodino — APPROVED** [review]

**Comment by KorbinianK** [comment]
closes #16468

**Pull request merged**
