### PR TITLE
 docs(website): add another sepolia faucet

### PR DESCRIPTION
**Pull request by StarryNight777**
Although there are already three claim faucet sites in the official guide, I see that there are still many community members who can't claim faucet 
https://www.infura.io/faucet
Only need to register, you can claim 0.5 ETH per day

### CODE REVIEW

**Comment by d1onys1us** [comment]
Thanks @StarryNight777 , first please check CONTRIBUTING.md for proper PR titles, this should be something like docs(website): add another sepolia faucet

Second, looks like you need to rebase your branch against main, there is a large code diff here. Let me know if you need help.

**Comment by StarryNight777** [comment]
Since this is my first time posting content on github, I apologize for the
trouble I caused you, I have made changes, please check.

Or do I need to delete the content I'm posting now and re-post it?

dave | d1onys1us ***@***.***> 於 2023年4月1日週六 上午3:22寫道：

**Comment by dantaik** [comment]
This is goo big of a PR. Sorry I cannot approve it...

**Comment by d1onys1us** [comment]
closing this PR because it is too big. i would suggest opening a new PR, and make sure when you create the branch that you are creating it from the main branch which is up to date. and then make the small change, and we can approve it. thanks!

**Pull request closed without merging**
