### PR TITLE
feat(website): automatically publish latest blog posts to website

### PR DESCRIPTION
**Pull request by Jaapiehetaapie**
This only fetches the posts at buildtime

### CODE REVIEW

**Comment by dantaik** [comment]
This is fine for now, but assuming this repository is stable enough and there is no requirement redeploy, then this solution will not work. I still prefer the dynamic loading approach.

**Comment by dantaik** [comment]
This is fine for now, but assuming this repository is stable enough and there is no requirement redeploy, then this solution will not work. I still prefer the dynamic loading approach.

**Comment by dantaik** [comment]
This is fine for now, but assuming this repository is stable enough and there is no requirement redeploy, then this solution will not work. I still prefer the dynamic loading approach.

**Comment by dantaik** [comment]
This is fine for now, but assuming this repository is stable enough and there is no requirement redeploy, then this solution will not work. I still prefer the dynamic loading approach.

**Comment by dantaik** [comment]
> This only fetches the posts at buildtime

This is fine for now, but assuming this repository is stable enough and there is no requirement redeploy, then this solution will not work. I still prefer the dynamic loading approach.

**Comment by dantaik** [comment]
> This only fetches the posts at buildtime

This is fine for now, but assuming this repository is stable enough and there is no requirement redeploy, then this solution will not work. I still prefer the dynamic loading approach.

**Comment by Jaapiehetaapie** [comment]
https://github.com/taikoxyz/taiko-mono/pull/13169#issuecomment-1433330747
It was mentioned here that fetching at build time would be the best option.

**Comment by dantaik** [comment]
> [#13169 (comment)](https://github.com/taikoxyz/taiko-mono/pull/13169#issuecomment-1433330747) It was mentioned here that fetching at build time would be the best option.

I see it differently. 

BTW, have we already merged a PR of yours that automatically fetch the data in real time? It is in production, isn't it?

**Comment by wolfderechter** [comment]
> BTW, have we already merged a PR of yours that automatically fetch the data in real time? It is in production, isn't it?

That PR was reverted with https://github.com/taikoxyz/taiko-mono/pull/13169 because of some issues

**Comment by Jaapiehetaapie** [comment]
I think this may be a good solution. But I think it's good to extract the 'on schedule' to a new workflow file and maybe it's needed to add some secret code to the api, otherwise everyone can call it.

**Comment by Jaapiehetaapie** [comment]
If using node it is needed to commit the changes to the repository. So I think it's better to go with the API way. We could also setup an vervel cron job, but I think it's better to have everything in GitHub actions. Thoughts?

**Pull request closed without merging**
