### PR TITLE
fix(website): revert auto-fetch blog posts on home page

### PR DESCRIPTION
**Pull request by dionysuzx**
This reverts commit 9fbf10214f531556dff8a1b591f76e7f71a580e2.

This PR will fix the site freezing on mobile. Right now the site is frozen / animation is blocked by the loading of the script. Probably some async/sync thing we need to fix. Tagging @Jaapiehetaapie for visibility.

### CODE REVIEW

**Comment by d1onys1us** [comment]
Also @Jaapiehetaapie , for your knowledge, I believe the correct way to do this would be at build time. So we don't even need to wait for a mirror API call, means we don't rely on that API if it is down, and also faster performance. We can store the json information locally. I can certainly take on this change (or another contributor), but if you're up for it, I think that's a better solution. If it is a GitHub action, I believe we can click the action in the GitHub UI as well to invoke the job, in case we need to re-fetch the blog posts.

**Comment by Jaapiehetaapie** [comment]
> Also @Jaapiehetaapie , for your knowledge, I believe the correct way to do this would be at build time. So we don't even need to wait for a mirror API call, means we don't rely on that API if it is down, and also faster performance. We can store the json information locally. I can certainly take on this change (or another contributor), but if you're up for it, I think that's a better solution. If it is a GitHub action, I believe we can click the action in the GitHub UI as well to invoke the job, in case we need to re-fetch the blog posts.

Sorry for the inconvenience i caused. I could give it a shot, but pretty new to this, so don't know if i will manage.

**Review by RogerLamTd — APPROVED** [review]

**Review by shadab-taiko — APPROVED** [review]

**Comment by dantaik** [comment]
> Also @Jaapiehetaapie , for your knowledge, I believe the correct way to do this would be at build time. So we don't even need to wait for a mirror API call, means we don't rely on that API if it is down, and also faster performance. We can store the json information locally. I can certainly take on this change (or another contributor), but if you're up for it, I think that's a better solution. If it is a GitHub action, I believe we can click the action in the GitHub UI as well to invoke the job, in case we need to re-fetch the blog posts.

I'd rather to fetch the data in real time as in the future, we won't do frequent redeployment at all.

**Comment by shadab-taiko** [comment]
> > Also @Jaapiehetaapie , for your knowledge, I believe the correct way to do this would be at build time. So we don't even need to wait for a mirror API call, means we don't rely on that API if it is down, and also faster performance. We can store the json information locally. I can certainly take on this change (or another contributor), but if you're up for it, I think that's a better solution. If it is a GitHub action, I believe we can click the action in the GitHub UI as well to invoke the job, in case we need to re-fetch the blog posts.
> 
> I'd rather to fetch the data in real time as in the future, we won't do frequent redeployment at all.

To do this maybe we can create an lambda function that can cache the results of this API and update it regularly.

**Pull request merged**
