### PR TITLE
feat: add theme switch on website home page

### LINKED ISSUE #13028: fix(website): toggle theme button only appears on mobile screens
### Describe the bug

I can't find the toggle button to toggle between light and dark mode on the website, only on mobile screens it appears in the dropdown menu

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

### PR DESCRIPTION
**Pull request by shadab-taiko**
Fixes #13028

### CODE REVIEW

**Review by dong77 — APPROVED** [review]

**Review by RogerLamTd — APPROVED** [review]

**Comment by RogerLamTd** [comment]
Looks good! Might want to make it a toggle button like the one on the bridge at the top of the page? Could make it easier to find and access.

**Review by dantaik — APPROVED** [review]

**Comment by wolfderechter** [comment]
> Looks good! Might want to make it a toggle button like the one on the bridge at the top of the page? Could make it easier to find and access.

I agree, it should be on top of the page, it's way too hard to find right now

**Comment by shadab-taiko** [comment]
> > Looks good! Might want to make it a toggle button like the one on the bridge at the top of the page? Could make it easier to find and access.
> 
> I agree, it should be on top of the page, it's way too hard to find right now
@RogerLamTd @wolfderechter 
The [Nextra](https://nextra.site/) theme that we are using places it like so and thus I have replicated it.

**Comment by Eleleth77** [comment]
agreed. Main page top right

**Pull request merged**
