### PR TITLE
feat(bridge): add ttko to dropdown

### LINKED ISSUE #14235: Add TTKO to the bridge app in the dropdown
### Describe the feature request

image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 2manslkh**

### CODE REVIEW

**Comment by d1onys1us** [comment]
@2manslkh @jscriptcoder any updates on this?

**Comment by 2manslkh** [comment]
@d1onys1us seems like there is a PR for it for bridge ui v2

**Comment by d1onys1us** [comment]
> @d1onys1us seems like there is a PR for it for bridge ui v2

is there any harm in adding this @jscriptcoder? or do you suggest we close it?

**Comment by jscriptcoder** [comment]
I'd say we can add it to the current bridge

**Comment by cyberhorsey** [comment]
This will add TTKO and not TTKOe, and be hardcoded for both bridges. It's better to add it as an environment variable.

**Pull request closed without merging**
