### PR TITLE
docs(website): very minor Update enable-a-prover.mdx

### PR DESCRIPTION
**Pull request by QustomQure**
Just updated line as it is in client. Which was outdated in docs

### CODE REVIEW

**Review by dantaik — APPROVED** [review]

**Comment by 2manslkh** [comment]
overlaps with #14236

**Comment by QustomQure** [comment]
> overlaps with #14236

I checked and it is not :)

**Comment by 2manslkh** [comment]
sorry i was referring to #14233. But this PR is valid

**Comment by d1onys1us** [comment]
thanks for the PR. as kenk said we have it overlapping another, so will close this one.

**Pull request closed without merging**
