### PR TITLE
feat(taikoon): taikoon ui setup

### PR DESCRIPTION
**Pull request by bearni95**
- [x] Bring over former `frontend` package
- [x] Adapt into monorepo's file structure & pnpm
- [x] Github Actions

### Checklist
- [x] Make the CSV and JSON whitelist files gitignored
- [x] Use viem's `zeroAddress`
- [x] Use viem's `Address` type
- [x] Implement texts using i18n
- [x] Replace `classess` export with `$$props.class`
- [x] No in-line tailwind css
- [x] Check daisyUI for collapse component
- [x] Ceanup unused errors
- [x] Move IPFS gateway to .env

### CODE REVIEW

**Review by dantaik — APPROVED** [review]

**Comment by KorbinianK** [comment]
I added several comments in the other PR, as the content seems to be identical, feel free to adress those here.

**Review by 0xoats — APPROVED** [review]
lgtm nit: maybe can add a .env.example for which env var is needed

**Review by bennettyong — APPROVED** [review]
lgtm. nit: add an .env.example for env vars needed

**Comment by dantaik** [comment]
> Implement texts using i18n
No need for localization

**Comment by dantaik** [comment]
Please also work with @KorbinianK (owner over Vercel projects) to set up auto-deployment for production and preview.

**Review by KorbinianK — APPROVED** [review]

**Pull request merged**
