### PR TITLE
feat(protocol): Additional integration tests, solidity bump, reduce TokenVault contract size

### PR DESCRIPTION
**Pull request by cyberhorsey**
This adds some additional integration tests, as well as updates Solidity to 0.8.18 so we can take advantage of the `named mapping parameters` function, which definitely helps readability on some of our more complex mappings, and removes the need for comments. It also fixes the linter/type errors on the new customError handling functions, as well as `hardhat-contract-sizer` to get to the bottom of the large contract which is failing our CICD randomly, which turned out to be the `TokenVault`, which is almost at `24.5kb` max contract size. I got it down to `22.7kb` with custom errors refactoring and slight modifications elsewhere, and now it seems to not fail our CICD.

However, `solhint` is not ready for named parameter mappings just yet:
https://github.com/protofire/solhint/issues/397

I can go ahead and undo those changes if we want to wait for `solhint` to be ready for us before we do this change.

@dantaik as well, in solidity `0.9.0`, `block.difficulty` will be removed from Solidity, which we use for setting the mixHash when proposing a block.

### CODE REVIEW

**Comment by dantaik** [comment]
> I can go ahead and undo those changes if we want to wait for solhint to be ready for us before we do this change.
No need to care about the solint errors.

> @dantaik as well, in solidity 0.9.0, block.difficulty will be removed from Solidity, which we use for setting the mixHash when proposing a block
I'll take a look.

**Review by dantaik — DISMISSED** [review]

**Comment by davidtaikocha** [comment]
> @dantaik as well, in solidity 0.9.0, block.difficulty will be removed from Solidity, which we use for setting the mixHash when proposing a block.

I believe we should use `block.prevrandao` instead, which was introduced in solidity 0.8.18:

image

**Comment by davidtaikocha** [comment]
And seems there are some errors in github action (`test:tokenomics`), hmm not sure if its because of the changes in this PR ?

**Comment by dantaik** [comment]
@cyberhorsey  I accidentally merged my PR onto yours before fixing test bugs. Please undo the last PR of mine.

**Comment by cyberhorsey** [comment]
> @cyberhorsey I accidentally merged my PR onto yours before fixing test bugs. Please undo the last PR of mine.

I have already commit on top of it :D. So far it actually seems the tests pass with your PR merged in, it is simply having issues with `solidity-coverage` library and the new 0.8.18 solidity changes as well. I will look at them tomorrow.

**Comment by davidtaikocha** [comment]
and looks like `abi.encodePacked` and `virtual` modifier will also be removed / disallowed in 0.9.0, seems we will also need to change them in current codebase later (not now maybe).
image

**Comment by dantaik** [comment]
> and looks like `abi.encodePacked` and `virtual` modifier will also be removed / disallowed in 0.9.0, seems we will also need to change them in current codebase later (not now maybe). image

Let's fix those later with new solidity features.

**Comment by cyberhorsey** [comment]
@dantaik @davidtaikocha `solidity-coverage` library is not ready for new solidity features, and the repo is potentially semi-abandoned (hanging open issues and PRs for quite some time).

I have submitted a PR to fix the repo so it works with `0.8.18`:
https://github.com/sc-forks/solidity-coverage/pull/783
But I am unsure if it will be merged in. In the meantime, I have changed our dependency to point to my fork.  Let me know if that isn't OK with you.

**Review by davidtaikocha — DISMISSED** [review]

**Comment by dantaik** [comment]
> I could also fork it under the taikoxyz org, or we could disable coverage.

I think we can fork the repo under taiko's account.

**Comment by cyberhorsey** [comment]
> > I could also fork it under the taikoxyz org, or we could disable coverage.
> 
> I think we can fork the repo under taiko's account.

OK, done

**Review by davidtaikocha — APPROVED** [review]

**Review by dantaik — APPROVED** [review]

**Pull request merged**
