### PR TITLE
fix(bridge-ui): show instant feedback when insufficient balance

### PR DESCRIPTION
**Pull request by deepaksing**
Before: 
 We currently disable the transfer bridge button, but the user might not realize the reason why the button remains disabled... 

After:
Shows instant warning whenever user types balance is lower than what's intended to be transferred (including estimated fees).

### CODE REVIEW

**Review by cyberhorsey — APPROVED** [review]

**Review by dantaik — APPROVED** [review]

**Review by shadab-taiko — APPROVED** [review]

**Comment by dantaik** [comment]
@jscriptcoder could you please take a look at this?

**Comment by jscriptcoder** [comment]
> @jscriptcoder could you please take a look at this?

Yeah, left a comment yesterday. We could merge it and then I take care of the change or @deepaksing might want to take a look.

**Comment by dantaik** [comment]
> > @jscriptcoder could you please take a look at this?
> 
> Yeah, left a comment yesterday. We could merge it and then I take care of the change or @deepaksing might want to take a look.

If it is a small change, we can change it?

**Comment by deepaksing** [comment]
> > @jscriptcoder could you please take a look at this?
> 
> Yeah, left a comment yesterday. We could merge it and then I take care of the change or @deepaksing might want to take a look.

ya, i can work on the required changes.

**Comment by dantaik** [comment]
> > > @jscriptcoder could you please take a look at this?
> > 
> > 
> > Yeah, left a comment yesterday. We could merge it and then I take care of the change or @deepaksing might want to take a look.
> 
> ya, i can work on the required changes.

Any update or ETA?

**Comment by jscriptcoder** [comment]
Can we hold off this PR until we have devnet to test?
cc: @deepaksing @dantaik

**Pull request closed without merging**
