### PR TITLE
fix(bridge-ui): transaction tab same width as bridge width

### PR DESCRIPTION
**Pull request by wolfderechter**
The transacton tab now has the same width as the bridge tab as requested per #7730.
image
image

### CODE REVIEW

**Comment by wolfderechter** [comment]
Cc @dantaik @shadab-taiko

**Review by dantaik — DISMISSED** [review]

**Comment by dantaik** [comment]
@shadab-taiko can we also make the min-height almost the same as the other tab?

**Comment by wolfderechter** [comment]
image
I was thinking about that before but didn't implement it. I added it now

**Comment by shadab-taiko** [comment]
Screenshot 2023-01-05 at 7 22 02 PM

This breaks once the transactions are populated.

**Comment by dong77** [comment]
Looks terrible

**Comment by wolfderechter** [comment]
@shadab-taiko you are right, I couldn't populate it locally but I think I fixed it. Do you know how I can populate locally? I think my .env isn't correct

**Comment by dong77** [comment]
If "claim" means an action, it should look like a button or have a different color.

**Comment by wolfderechter** [comment]
I think I got it, I set the min-height to that of the bridge tab when there are 0 transactions.
taikobridgenotransactions

And I don't set a min-height when there **are** transactions so it stays fit-content. The min-width gets set based on the bridge width but the width increases to fit-content when there are transactions.
taikobridgetransactions
@dantaik what do you think?

Perhaps in another pull request the 'From and To' tab can be merged, my solution should still work when that happens.

Let's hope my solution works in the testing environment as I'm not 100% sure.

**Comment by dantaik** [comment]
LGTM

**Comment by dantaik** [comment]
@shadab-taiko could you please verify if everything works?

**Review by shadab-taiko — APPROVED** [review]

**Comment by shadab-taiko** [comment]
Verified the transactions list with and without transactions. LGTM 🚀 .

Thanks @wolfderechter

**Review by dantaik — APPROVED** [review]

**Pull request merged**
