### PR TITLE
chore(branding): add Reddit badge to README

### PR DESCRIPTION
**Pull request by papadritta**
This PR updates README with a new Reddit badge and makes the Taiko community more visible and accessible. The badge clickable provides a link to the Taiko Reddit community. This badge makes it easy for users to find and participate in the Taiko subreddit, fostering greater community interaction.

### CODE REVIEW

**Comment by KorbinianK** [comment]
Is anyone official involved with this subreddit? If not, we should not include it.

**Comment by papadritta** [comment]
@KorbinianK @d1onys1us The Taiko subreddit holds 1,8 K members and is in the top 15% by rank size, the news is updated regularly.

**Comment by d1onys1us** [comment]
We're not very active there so will leave it out. Thanks for the PR

**Comment by papadritta** [comment]
ok

**Pull request closed without merging**
