### PR TITLE
chore: Bridge Rebrand

### PR DESCRIPTION
**Pull request by smartprogrammer93**

### CODE REVIEW

**Comment by dantaik** [comment]
Could you please provide some background for these changes?

**Comment by smartprogrammer93** [comment]
Apologies, this was supposed to happen on CoreRollup repository and not here. I will explain more details in our meeting today

**Comment by dantaik** [comment]
@smartprogrammer93 I think maybe it's a good idea to modify our code directly to support different branding (names, icons, images)? What do you think :D

**Comment by smartprogrammer93** [comment]
@dantaik that sounds cool. We will have one of our front end engineers contribute here with the modification next week.

**Pull request closed without merging**
