### PR TITLE
refactor(website): hero animation with GSAP

### PR DESCRIPTION
**Pull request by wolfderechter**
Refactored the taikoGeom image animation with the [GSAP ](https://greensock.com/gsap/) library to make it smoother, clearer and better maintainable.

### CODE REVIEW

**Review by dantaik — DISMISSED** [review]

**Review by dionysuzx — DISMISSED** [review]

**Review by davidtaikocha — DISMISSED** [review]

**Comment by d1onys1us** [comment]
there are some merge conflicts @wolfderechter let me know if you need any help

**Comment by dantaik** [comment]
The animation is not as smooth as it used to be.

**Comment by d1onys1us** [comment]
have you considered the react-spring library maintained by poimandres? wonder if it is any smoother. poimandres maintains some good stuff. maybe a fun thing to look as well: https://github.com/pmndrs/react-spring

**Comment by d1onys1us** [comment]
@dantaik what about it is less smooth? did you try this URL: https://website-4nidotxwy-taikoxyz.vercel.app/

**Comment by dantaik** [comment]
> 

True, it's not as smooth as the current website deployment. I'm using a MacBook Air.

**Comment by wolfderechter** [comment]
I wanted to try using a framework made for animations to simplify the code but it seems like my own approach works better overal. I'll close this PR

**Pull request closed without merging**
