### PR TITLE
docs(website): fix duplicated docs page title

### PR DESCRIPTION
**Pull request by hairtail**
https://taiko.xyz/docs/reference/contract-documentation/L1/ProofVerifier

This PR removes the duplicated and useless page title item and changes the page title from `IProofVerifier` to `IProofVerifier & ProofVerifier `.

### CODE REVIEW

**Review by dantaik — DISMISSED** [review]

**Comment by d1onys1us** [comment]
@hairtail thanks for your contribution ❤️ 

for auto-generated documentation, we do not want to manually edit any of these files. the contents of these files should always be the result of running the command: `pnpm -F protocol export:docs`. so, to fix this, we need to fix the handlebars template which parses the solidity files and generates the documentation, by removing the "title".

i created the branch showing you how to properly make the change, if you'd like: https://github.com/taikoxyz/taiko-mono/compare/fix-autogen-docs-remove-title?expand=1

1. https://github.com/taikoxyz/taiko-mono/compare/fix-autogen-docs-remove-title?expand=1#diff-3da56a5075c69802eb977f423c3f3d6a717e109efbed0e5d49ea2d943842fac2L1 -- remove "title" from the handlebars template
2. run `pnpm -F protocol export:docs` from the monorepo

**Review by dionysuzx — CHANGES_REQUESTED** [review]
please see my comment for the requested changes

**Comment by hairtail** [comment]
> please see my comment for the requested changes

Thanks for reply. I will update this PR with these comments and changes.

**Comment by hairtail** [comment]
> please see my comment for the requested changes

Updated.

**Review by davidtaikocha — APPROVED** [review]

**Review by dionysuzx — APPROVED** [review]

**Review by dantaik — APPROVED** [review]

**Pull request merged**
