### PR TITLE
feat(bridge-ui-v2): navigation support to swap-ui from bridge-ui

### PR DESCRIPTION
**Pull request by arularmstrong**
This PR adds a navigation bar for `swap` from the [Bridge UI](https://bridge.katla.taiko.xyz/), enabling seamless navigation between two apps. Notably, while a redirect from the [Swap UI](https://swap.katla.taiko.xyz/) to the [Bridge UI](https://bridge.katla.taiko.xyz/) already exists, this update addresses the lack of a reciprocal link and ensures improved user experience and navigation consistency. 

reference on [swap-ui](https://swap.katla.taiko.xyz/)
swap-ui-bridge-link

reference on [bridge-ui](https://bridge.katla.taiko.xyz/)
bridge-ui-swap-link

### CODE REVIEW

**Comment by KorbinianK** [comment]
@arularmstrong Thanks, very good idea.  Please fix the [linting issues](https://github.com/taikoxyz/taiko-mono/actions/runs/7958258406/job/21727467954?pr=15922) then we can merge it.

Run `pnpm svelte:check && pnpm lint:fix` to see all the issues

**Comment by arularmstrong** [comment]
Sure, fixing the lint issues.

**Comment by arularmstrong** [comment]
make sure to add `PUBLIC_DEFAULT_SWAP_URL=https://swap.katla.taiko.xyz/` over the env.

**Review by KorbinianK — APPROVED** [review]

**Comment by KorbinianK** [comment]
@arularmstrong approved. But please note, that the changes won't be visible before our next bridge release.

**Review by dantaik — APPROVED** [review]

**Pull request merged**
