### PR TITLE
fix(relayer):  Save the Key values in .env file

### PR DESCRIPTION
**Pull request by cryptoryda**
### Save Mysql key values in environment file 

```javascript
  environment:
    #save the key values in .env file
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
```

### CODE REVIEW

**Review by xiaodino — CHANGES_REQUESTED** [review]
Why `packages/protocol/contracts/bridge/Bridge.sol` is being deleted?

**Comment by cryptoryda** [comment]
2 changes in one PR is not allowed this is why I delete bridge.sol and make separate PR

**Comment by cyberhorsey** [comment]
This PR should not have Bridge.sol being deleted.

**Comment by cryptoryda** [comment]
You mean close this PR and reopen with just the .env change or readd the bridge.sol ?

**Comment by cyberhorsey** [comment]
> You mean close this PR and reopen with just the .env change or readd the bridge.sol ?

Either one, but you should not be deleting Bridge contracts. Why would we want our contract deleted?

**Comment by cryptoryda** [comment]
Understood

**Comment by cryptoryda** [comment]
Closed

**Pull request closed without merging**
