### PR TITLE
feat(website): add AIT Protocol to ecosystem

### LINKED ISSUE #14794: Add AIT Protocol to Taiko's ecosystem
### Title of your project

AIT Protocol

### Short (1-2 sentence) description of your project

AIT Protocol is the first’s Web3 data infrastructure focusing on AI data annotations, leverages blockchain technology to deliver a trustless and cross-border labor market being strategically incentivized by crypto economics and having instant cross-nation payment settlements.

### Link to your project

https://ait.tech/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

https://explorer.jolnir.taiko.xyz/address/0x802e73F54D092D2F3f237bC5Dba74fFF7cF89BE5

### Upload a quality logo to your project

https://drive.google.com/file/d/1qWzB_BO6b7t3_KGcKWl2ORDqMocu2bjO/view

### PR DESCRIPTION
**Pull request by 2manslkh**
Closes #14794
cc: @AITProtocol

### CODE REVIEW

**Review by dionysuzx — DISMISSED** [review]

**Comment by MarcusWentz** [comment]
Logo is not rendering. Was the logo included? Maybe the path is broken?
logo

**Review by MarcusWentz — CHANGES_REQUESTED** [review]
https://github.com/taikoxyz/taiko-mono/pull/14868#issuecomment-1741818112

**Review by dantaik — DISMISSED** [review]

**Comment by AITProtocol** [comment]
> [#14868 (comment)](https://github.com/taikoxyz/taiko-mono/pull/14868#issuecomment-1741818112)

AITProtocol-512x512

I've re-added the logo

**Comment by AITProtocol** [comment]
> [#14868 (comment)](https://github.com/taikoxyz/taiko-mono/pull/14868#issuecomment-1741818112)

AITProtocol_512x512

Please use this logo in the ecosystem

**Comment by AITProtocol** [comment]
> Logo is not rendering. Was the logo included? Maybe the path is broken? logo

AITProtocol_512x512
Please use this logo in the ecosystem

**Review by dionysuzx — APPROVED** [review]

**Review by MarcusWentz — APPROVED** [review]

**Review by fahimMuhamma — COMMENTED** [review]
Good

**Review by fahimMuhamma — COMMENTED** [review]
Good

**Pull request merged**
