### PR TITLE
feat(guardianproverhealthcheck): Guardian prover UI

### PR DESCRIPTION
**Pull request by cyberhorsey**
simple guardian prover dashboard, this PR contains an ugly demo video. just adds all the functionaltiy for consumign the guardian-prover API and displaying the health check and statistic data.

This dashboard should demonstrate health checks and uptime availability for our guardian provers, and is three parts:

1) a Golang service that routinely calls the services for health checks and stores them in the DB
2) a Golang service that, every 24 hours, indexes the health checks and calculates daily stats, storing them in the DB.
3) a Svelte frontend that consumes these APis to display health check and uptime availability.

further PR will style it up before deployment.

https://github.com/taikoxyz/taiko-mono/assets/113397187/4a823af6-67ca-4f19-85a7-792669d014af

@KorbinianK maybe when the bridge work is completed for Alpha6 styling this can be something you can assist with, as this tool will make it for Mainnet as well, and should look professional :). In the meantime I will do what I can while you are occupied.

### CODE REVIEW

**Comment by dantaik** [comment]
Great progress Jeff. Could you make sure we see the most recent 200 blocks on the landing pages each with a indicator whether all guardian provers signs the same block hash or there is an different view for a block. We can click on a block to see what each guardian has send.

We can also have a liveness stats for each guardian  - the guardian is considered offline if there is no signature for a block within 15 seconds.

**Comment by cyberhorsey** [comment]
> Great progress Jeff. Could you make sure we see the most recent 200 blocks on the landing pages each with a indicator whether all guardian provers signs the same block hash or there is an different view for a block. We can click on a block to see what each guardian has send.
> 
> We can also have a liveness stats for each guardian - the guardian is considered offline if there is no signature for a block within 15 seconds.

can do!

**Review by dantaik — APPROVED** [review]

**Comment by cyberhorsey** [comment]
Waiting on redeploy of network  with latest code and client changes to finish off this tool.

**Comment by dantaik** [comment]
@cyberhorsey , sorry that you need to rebase this branch.

**Comment by cyberhorsey** [comment]
> @cyberhorsey , sorry that you need to rebase this branch.

All good, I will wait until some PRs are merged and new internal devnet is deployed with all the protocol changes, as that will mandate changes to this PR anyways, then create a new PR instead.

**Pull request closed without merging**
