### PR TITLE
chore(bridge-ui): remove deprecated bridge UI

### PR DESCRIPTION
**Pull request by KorbinianK**
On 31st Oct. the old bridge UI will be deprecated and go offline.

The code has been archived in a separate repository

### CODE REVIEW

**Review by davidtaikocha — DISMISSED** [review]
And shall we also update the project README?

**Comment by KorbinianK** [comment]
> And shall we also update the project README?

It's not listed in the Readme anymore is it?

**Comment by davidtaikocha** [comment]
> > And shall we also update the project README?
> 
> It's not listed in the Readme anymore is it?

image
here?

**Comment by d1onys1us** [comment]
> > And shall we also update the project README?
> 
> It's not listed in the Readme anymore is it?

It is on the bottom of the README yeah

**Review by davidtaikocha — APPROVED** [review]

**Review by dionysuzx — APPROVED** [review]

**Pull request merged**
