### PR TITLE
chore(bridge): change homepage hero for mobile view

### LINKED ISSUE #399: update website homepage hero for mobile view
Great first issue for anyone who is familiar with tailwind / css. Something like this, but with the text aligned to the left I'm thinking:

Image

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issues :- 

closes #399 

## Changes made :- 

- Removing some of the CSS properties from index.tsx file.

### Before
206601346-4c299344-5feb-4e05-9dc6-47e4b5534b72

### After
Screenshot 2022-12-09 153931

### CODE REVIEW

**Comment by Rishav1707** [comment]
Please run the workflows awaiting approval... @d1onys1us @dong77 @mfinestone @RogerLamTd

**Comment by d1onys1us** [comment]
image
As long as we are keeping that grid drawing below, I think it looks better as is. I think it would make sense to left-align things if we put that grid drawing right-aligned to the text and button. does that make sense?

**Comment by wolfderechter** [comment]
That makes sense and I agree!

**Comment by Rishav1707** [comment]
I have committed the required changes... @d1onys1us @wolfderechter @dong77 @schlusslicht 
Please run the workflows.

### Screenshots
Screenshot 2022-12-10 074238

**Comment by d1onys1us** [comment]
> I have committed the required changes... @d1onys1us @wolfderechter @dong77 @schlusslicht 
> Please run the workflows.
> 
> ### Screenshots
> Screenshot 2022-12-10 074238
> 

Hi @Rishav1707 I don't see what the difference is between this and the current homepage, aside from the horizontal line. I believe we want to put the grid pattern "behind" the text, or leave it as is.

**Review by dantaik — APPROVED** [review]

**Comment by Rishav1707** [comment]
@dantaik @shadab-taiko  Please review my changes...

Screenshot 2022-12-10 195934

**Comment by d1onys1us** [comment]
> @dantaik @shadab-taiko  Please review my changes...
> 
> 
> 
> Screenshot 2022-12-10 195934
> 
> 

@Rishav1707 Did you see my comment? We might not need this change in the current state, and instead would either 1) keep it the same or 2) move the grid background "behind" the text.

**Comment by Rishav1707** [comment]
Thanks for giving me an opportunity to contribute.

**Pull request closed without merging**
