### PR TITLE
feat(protocol): create SharedTaikoTokenVault.sol

### PR DESCRIPTION
**Pull request by dantaik**

### CODE REVIEW

**Comment by adaki2004** [comment]
Seems pretty straightforward but i'll add couple of tests today.

**Comment by adaki2004** [comment]
Did not we discuss last week this will be a multisig ? 🤔

**Comment by dantaik** [comment]
> Did not we discuss last week this will be a multisig ? 🤔

Ah, you are right.

**Comment by adaki2004** [comment]
> Seems pretty straightforward but i'll add couple of tests today.

@dantaik modified the tests to use this contract.

**Pull request closed without merging**
