### PR TITLE
feat(repo): don't run workflows on release-please branches

### PR DESCRIPTION
**Pull request by RogerLamTd**
should stop all workflows from running on release-please branches except typo and pr title, will restore merge-gatekeeper after testing

### CODE REVIEW

**Comment by dantaik** [comment]
Roger, I also don't want to run workflow when a PR is still draft.

**Comment by RogerLamTd** [comment]
> Roger, I also don't want to run workflow when a PR is still draft.

Ok I'll restore that!

**Comment by dionysuzx** [comment]
just making sure was this tested in a forked repo? otherwise LGTM.

**Review by dionysuzx — APPROVED** [review]

**Comment by RogerLamTd** [comment]
> just making sure was this tested in a forked repo? otherwise LGTM. (i think it is okay to test on this main repo too if easier)

planning on merging a docs-site release to test, fairly straightforward

**Review by davidtaikocha — APPROVED** [review]

**Comment by dionysuzx** [comment]
I think this solution looks totally fine, thus approved. But if you want, this is an alternative approach:

```
# .github/actions/exit-if-draft/action.yml
name: "Exit if Draft PR"
description: "Exits workflow if PR is in draft mode"
runs:
  using: "composite"
  steps:
    - name: Exit if draft PR
      shell: bash
      run: |
        if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
          echo "Draft PR detected. Exiting workflow."
          exit 0
        fi
```

usage:

```
# .github/workflows/your-workflow.yml
jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if Draft PR
        uses: ./.github/actions/exit-if-draft

      # Add your remaining steps here
```

**Pull request merged**
