### PR TITLE
chore(protocol): recover the out-of-data tcb info error.

### PR DESCRIPTION
**Pull request by smtmfft**
Missed 1 recoverable error type OUT_OF_DATE, update tcb file for testnet workaound.

### CODE REVIEW

**Comment by smtmfft** [comment]
Hi, @adaki2004 can we also put Automata behind proxy? then the fix upgrade is easier.
@davidtaikocha What's your opinion?

**Comment by davidtaikocha** [comment]
> Hi, @adaki2004 can we also put Automata behind proxy? then the fix upgrade is easier. @davidtaikocha What's your opinion?

i think we should

**Comment by adaki2004** [comment]
> Hi, @adaki2004 can we also put Automata behind proxy? then the fix upgrade is easier. @davidtaikocha What's your opinion?

I can modify these in the script, to use proxies with these:
```
        // No need to proxy these, because they are 3rd party. If we want to modify, we simply
        // change the registerAddress("automata_dcap_attestation", address(attestation));
        P256Verifier p256Verifier = new P256Verifier();
        SigVerifyLib sigVerifyLib = new SigVerifyLib(address(p256Verifier));
        PEMCertChainLib pemCertChainLib = new PEMCertChainLib();
        AutomataDcapV3Attestation automateDcapV3Attestation =
            new AutomataDcapV3Attestation(address(sigVerifyLib), address(pemCertChainLib));
```

Question:
`All` or just `automata` ? Since they are just libs (static!?) i guess `automata` is enough ?

**Comment by adaki2004** [comment]
Please see: https://github.com/taikoxyz/taiko-mono/pull/16867/files
@davidtaikocha  if you wanna deploy, just uncomment everything else in `DeployOnL1.sol` except the `automata` part and you can call it a day :P (But i guess you know better how to deploy).

**Review by dantaik — APPROVED** [review]

**Review by adaki2004 — APPROVED** [review]

**Pull request merged**
