### PR TITLE
chore(protocol): use american english

### PR DESCRIPTION
**Pull request by n1punp**
The words "optimize", "humanize" are used. So, I assume American english should used for consistency.

Adaptor is British, and adapter is American.

### CODE REVIEW

**Review by dantaik — APPROVED** [review]

**Comment by KorbinianK** [comment]
@d1onys1us we should think twice about accepting typo/spelling PRs.

**Review by dionysuzx — APPROVED** [review]

**Review by dionysuzx — CHANGES_REQUESTED** [review]
thank you for your PR, we see this as an improvement. however, we did not say anywhere that we prefer american english > british english.

could you find a spot for this in CONTRIBUTING.md?

**Comment by n1punp** [comment]
It is mainly for consistency throughout the codebase. You can see here for example:
https://github.com/taikoxyz/taiko-mono/blob/main/packages/protocol/contracts/L1/TaikoData.sol#L168 (optimize is american, whereas british would be optimise).

Feel free to close it if you think it's not important, but I think would be best to have consistency overall, so there are no cases like name collision or mispellings due to langauge.

**Comment by n1punp** [comment]
Can you clarify what you mean by "could you find a spot for this in CONTRIBUTING.md?"

**Comment by KorbinianK** [comment]
> Can you clarify what you mean by "could you find a spot for this in CONTRIBUTING.md?"

Update the CONTRIBUTING.md file to specifiy we are preferring American English, so future contributers have a reference.

**Review by dionysuzx — APPROVED** [review]

**Pull request merged**
