### PR TITLE
chore(repo): typos in taikoxyz / taiko-mono

### PR DESCRIPTION
**Pull request by soandwhat**
Fixed grammatical errors in code comments, as noted in issue #16761.

### CODE REVIEW

**Comment by dantaik** [comment]
Thank you for your contribution @soandwhat . However, we prefer to correct these typos when affected files are modified, and we hope not to have PRs that modified more than one package.

**Comment by soandwhat** [comment]
> Thank you for your contribution @soandwhat . However, we prefer to correct these typos when affected files are modified, and we hope not to have PRs that modified more than one package.

No problem mate. I need to close this PR?

**Comment by d1onys1us** [comment]
closing this PR. we don't accept typo PRs because it is too opinionated. instead you must change our typos CICD config. check it out under .github/workflows/*

**Comment by alexanderblv** [comment]
> closing this PR. we don't accept typo PRs because it is too opinionated. instead you must change our typos CICD config. check it out under .github/workflows/*

I have already opened a PR that fully satisfies the requirement .github/workflows/* (https://github.com/taikoxyz/taiko-mono/issues/16747).

Waiting for approval.

**Pull request closed without merging**
