### PR TITLE
feat(website): Add Copy Button for Prover Addresses

### PR DESCRIPTION
**Pull request by samui68400**
Implemented a **copy button** next to each prover address, allowing users to easily copy the address in the format PROVER_ENDPOINTS=http://[address]:[port]. 

**This simplifies the process of filling the .env file.** 

In addition, I'm planning to add a feature that lets you copy the addresses of all provers at once. 

Community feedback on this improvement is welcome.

### CODE REVIEW

**Comment by samui68400** [comment]
Hello team! I've made some enhancements to provide an easier way to copy the prover addresses. 

I noticed there are some Vercel deployment authorizations required and also a linting issue. 
Can someone assist with the Vercel deployments? 
Also, I'll work on resolving the linting and file conflicts. 
Would appreciate a review once those are addressed. Thank you!

**Comment by samui68400** [comment]
I've resolved the merge conflicts in this pull request, and it's now ready for your review. The changes include the addition of a copy button feature next to each prover address, simplifying the process of copying addresses in the format PROVER_ENDPOINTS=http://[address]:[port].

Your feedback and approval are greatly appreciated. Once you're satisfied with the changes, I'd kindly request you to merge the pull request.

Thank you for your time and assistance!

**Comment by samui68400** [comment]
I'm still waiting for a review guys

**Comment by 2manslkh** [comment]
Could you merge this into #15048 if its possible? Thanks

**Comment by samui68400** [comment]
Hi team, I don't have merge authorization from Wolfderechter to merge my pull request into #15048. Could you provide instructions on how to proceed?

**Comment by dantaik** [comment]
Please notice that the website code has been migrated to https://github.com/taikoxyz/website, please submit PRs to the new repository. Thank you.

**Pull request closed without merging**
