### PR TITLE
fix(bridge ui): SelectToken symbol not update

### PR DESCRIPTION
**Pull request by chezhe**
Fix SelectToken symbol not updated when selecting HORSE

Screenshot 2023-01-06 at 19 56 17

### CODE REVIEW

**Comment by dantaik** [comment]
@shadab-taiko could you please verify the change?

**Comment by shadab-taiko** [comment]
I couldn't replicate this issue. Also, the fix in this PR doesn't seem to be solving anything. @chezhe could you give some more details about what the intended behaviour of this change should be?

**Comment by chezhe** [comment]
https://user-images.githubusercontent.com/2902414/211497615-041f7cf7-63a2-48b7-bb63-35a9a6ed77ef.mov

This video is captured on https://bridge.a1.taiko.xyz/, when I select HORSE token, the icon changed, but the symbol not.

**Comment by shadab-taiko** [comment]
@chezhe could you explain how removing the `toUpperCase()` fixes this? I don't see why this change should fix the issue.

**Comment by chezhe** [comment]
I can't, I don't use svelte.is, but it fixes the problem actually.

**Comment by cyberhorsey** [comment]
@chezhe what browser are you using?

**Comment by cyberhorsey** [comment]
> I can't, I don't use svelte.is, but it fixes the problem actually. And in fact, there's no need to uppercase the symbols, it's uppercase by default.

It's for when we add dynamic tokens for Mainnet and not just hard-coded ETH and HORSE.

**Comment by chezhe** [comment]
> @chezhe what browser are you using?

Chrome: Version 108.0.5359.124 (Official Build) (arm64)

**Comment by dantaik** [comment]
@cyberhorsey @shadab-taiko  what about this PR?

**Comment by shadab-taiko** [comment]
> @cyberhorsey @shadab-taiko what about this PR?

I think we can close this PR because the fix doesn't seem to be fixing the actual problem. Trying to reproduce this issue, will put in a fix after that.

**Pull request closed without merging**
