### PR TITLE
fix(bridge-ui): renamed configuredCustomToken to configuredCustomTokens

### PR DESCRIPTION
**Pull request by arularmstrong**
This PR addresses an inconsistency in the project's configuration file naming. The file in the config directory was originally named configuredCustomToken, while references elsewhere used configuredCustomTokens. To maintain consistency, I've renamed the file to configuredCustomTokens, aligning it with the Readme and other references.

### CODE REVIEW

**Comment by KorbinianK** [comment]
[There is zero changes.](https://github.com/taikoxyz/taiko-mono/pull/15905/files) Next time double check before you open a PR, otherwise we will treat it as spam

**Review by KorbinianK — CHANGES_REQUESTED** [review]
@arularmstrong I have reopened the PR again as you were right after all. It seems due to some rebase the fix has been reverted. But the package has since moved to bridge-ui now, please rebase your PR to the latest main and then we can merge it.

**Comment by arularmstrong** [comment]
@KorbinianK the PR is rebased with latest main

**Review by KorbinianK — APPROVED** [review]

**Review by KorbinianK — CHANGES_REQUESTED** [review]
@arularmstrong You need to remove the incorrectly named ones as well please.

**Review by KorbinianK — APPROVED** [review]

**Review by davidtaikocha — APPROVED** [review]

**Pull request merged**
