### PR TITLE
chore(relayer): prevent indexing halts and add error monitoring metrics

### PR DESCRIPTION
**Pull request by xiaodino**
Updated error handling in the block indexing code to use slog.Error for logging errors instead of wrapping and returning them.

This ensured that if the indexer encounters an error with a specific transaction, it logs the error after retries and continues processing the remaining transactions. This prevents the indexing process from halting due to individual transaction errors.

### CODE REVIEW

**Review by davidtaikocha — APPROVED** [review]

**Comment by cyberhorsey** [comment]
why?

**Review by dantaik — APPROVED** [review]

**Comment by xiaodino** [comment]
> Updated error handling in the block indexing code to use slog.Error for logging errors instead of wrapping and returning them.
> 
> This ensured that if the indexer encounters an error with a specific transaction, it logs the error after retries and continues processing the remaining transactions. This prevents the indexing process from halting due to individual transaction errors.

Updated the description: 
Updated error handling in the block indexing code to use slog.Error for logging errors instead of wrapping and returning them.
This ensured that if the indexer encounters an error with a specific transaction, it logs the error after retries and continues processing the remaining transactions. This prevents the indexing process from halting due to individual transaction errors.

**Comment by xiaodino** [comment]
> why?

Updated the description:
Updated error handling in the block indexing code to use slog.Error for logging errors instead of wrapping and returning them.
This ensured that if the indexer encounters an error with a specific transaction, it logs the error after retries and continues processing the remaining transactions. This prevents the indexing process from halting due to individual transaction errors.

**Comment by cyberhorsey** [comment]
> > why?
> 
> Updated the description: Updated error handling in the block indexing code to use slog.Error for logging errors instead of wrapping and returning them. This ensured that if the indexer encounters an error with a specific transaction, it logs the error after retries and continues processing the remaining transactions. This prevents the indexing process from halting due to individual transaction errors.

But now we don't know about errors and can miss messages, because we will index blocks past the one that contained the error. Simply logging it isn't enough. If you want to make this more robust, you need to log it and update a Prometheus metric then create an alert tied to the metric with the message type that is being errored.

With this change, we could miss any number of messages, and never know unless we happen to be actively reading logs.

**Comment by xiaodino** [comment]
> > > why?
> > 
> > 
> > Updated the description: Updated error handling in the block indexing code to use slog.Error for logging errors instead of wrapping and returning them. This ensured that if the indexer encounters an error with a specific transaction, it logs the error after retries and continues processing the remaining transactions. This prevents the indexing process from halting due to individual transaction errors.
> 
> But now we don't know about errors and can miss messages, because we will index blocks past the one that contained the error. Simply logging it isn't enough. If you want to make this more robust, you need to log it and update a Prometheus metric then create an alert tied to the metric with the message type that is being errored.
> 
> With this change, we could miss any number of messages, and never know unless we happen to be actively reading logs.
> 
> With this change, what is the current plan for reindexing blocks where messages had errors? What is our plan for being notified about them?


Thank you for the feedback. The primary goal of this PR is to prevent the indexing process from halting due to individual transaction errors. Here's how we address your concerns:

Key Changes:
1. Error Logging and Metrics:
- Added Prometheus metrics to track errors for each event type:
```message_sent_events_after_retry_error_count```
```message_status_changed_events_after_retry_error_count```
```chain_data_synced_events_after_retry_error_count```
```message_processed_events_after_retry_error_count```
These metrics increment when errors are logged after retries.

2. Alerting:
We will set up Prometheus alerts based on the new error metrics. This ensures we are promptly notified of errors and can take action.

3. Reindexing Strategy:
We have an existing crawler that reindexes data. When an error is logged, it is tracked by Prometheus. This ensures any missed messages are eventually processed.

Next Steps:
1. Implement Alerts:
- Set up Prometheus alerts based on the new error metrics to ensure timely notifications.
Ensure Crawler Reindexing:
2. Ensure Crawler Reindexing:
- Ensure the crawler to reindex blocks.

Let me know if you have any further suggestions or concerns.

**Review by cyberhorsey — APPROVED** [review]

**Pull request merged**
