### PR TITLE
chore(repo): remove Merge Gatekeeper

### PR DESCRIPTION
**Pull request by davidtaikocha**
Remove the `Merge Gatekeeper` (temply), which is also costing us too much computing resource / time / money, seems once a PR is merged, right now some pending PRs merge gatekeeper actions will also be triggered, and each will run >3mins, and the one  in snaefell ui will run ~20 mins.

image

image

### CODE REVIEW

**Comment by davidtaikocha** [comment]
cc @d1onys1us

**Review by YoGhurt111 — APPROVED** [review]

**Review by dantaik — APPROVED** [review]

**Comment by d1onys1us** [comment]
> Remove the `Merge Gatekeeper` (temply), which is also costing us too much computing resource / time / money, seems once a PR is merged, right now some pending PRs merge gatekeeper actions will also be triggered, and each will run >3mins, and the one in snaefell ui will run ~20 mins.
> 
> image image

@davidtaikocha do you have any links to jobs or PRs I can look at to investigate? if merge-gatekeeper is buggy maybe i can re-implement it by hand. it's not a complicated job (just make sure every triggered workflow passes).

we just have to keep in mind that now a PR can be merged in without status check passing until this gets fixed, because i don't think there is any other solution for required status checks with a monorepo right now.

**Comment by d1onys1us** [comment]
also want to link this github issue which has some ideas: https://github.com/orgs/community/discussions/26251

**Comment by davidtaikocha** [comment]
> also want to link this github issue which has some ideas: https://github.com/orgs/community/discussions/26251
> 
> if we cannot fix whats wrong with merge-gatekeeper, i think we should refactor the jobs to use https://github.com/dorny/paths-filter; then we can add back all the important required jobs back to the required status checks of the monorepo, and they will skip if not triggered properly.
> 
> cc @kimo-ice in case you have any other ideas or suggestions.

like this one: https://github.com/taikoxyz/taiko-mono/actions/runs/11247389127 ?

**Pull request merged**
