### PR TITLE
test(protocol): Signal service foundry tests

### PR DESCRIPTION
**Pull request by cyberhorsey**
the `major_protocol_upgrade_rebase` branch had a `.only` on a SignalService test, so the tests werent actually running. Only a single test was
. Now that I've deleted that test, this shows that 6 of them are now failing, but they were always failing on your branch @dantaik , just hidden.

Should we just scrap the hardhat tests, or add another `.only` so they "appear" to pass? I'm in favor of just deleting them all rather than putting it any work to make them pass.

### CODE REVIEW

**Comment by dantaik** [comment]
@cyberhorsey  There are testing failures.

**Comment by cyberhorsey** [comment]
> @cyberhorsey There are testing failures.

Please read the main comment of this PR

**Comment by dantaik** [comment]
> 

Lets delete them.

**Comment by cyberhorsey** [comment]
> > 
> 
> Lets delete them.

Done, plus I changed the package.json commands, and Github Actions.

**Review by dantaik — APPROVED** [review]

**Pull request merged**
