### PR TITLE
docs(repo): fix all typos

### PR DESCRIPTION
**Pull request by momodaka**
### Description

use [typos](https://github.com/crate-ci/typos) to fix all typos issue

### Related issues

#16488

### CODE REVIEW

**Comment by dantaik** [comment]
@momodaka could you resolve the conflicts first

**Comment by momodaka** [comment]
> @momodaka could you resolve the conflicts first

👌, conflicts resolved

**Comment by dantaik** [comment]
@d1onys1us do you think it's OK for this PR to modify files in more than one package?

**Review by dantaik — APPROVED** [review]

**Comment by d1onys1us** [comment]
> @d1onys1us do you think it's OK for this PR to modify files in more than one package?

yes because repo is wide enough in scope to consume all these changes. so it's not confusing to see this in the changelog for each affected subpackage.

**Review by dionysuzx — APPROVED** [review]

**Review by RogerLamTd — APPROVED** [review]

**Pull request merged**
