### PR TITLE
fix(pos-dashboard): Fix lint errors and add pos-dashboard to lefthook.yaml

### PR DESCRIPTION
**Pull request by xiaodino**

### CODE REVIEW

**Comment by xiaodino** [comment]
test this please

**Review by dantaik — DISMISSED** [review]

**Comment by dantaik** [comment]
@xiaodino how about make linting and formating automated?

**Comment by xiaodino** [comment]
> @xiaodino how about make linting and formating automated?

Good idea. Added pos-dashboard to lefthook.yaml to enable linting and formating automation

**Comment by KorbinianK** [comment]
As @cyberhorsey commented in the other PR,this package is not used anymore since Jolnir. No need to work on this.

**Comment by xiaodino** [comment]
> As @cyberhorsey commented in the other PR,this package is not used anymore since Jolnir. No need to work on this.

If it's not used anymore, should we move it?

**Comment by d1onys1us** [comment]
> > As @cyberhorsey commented in the other PR,this package is not used anymore since Jolnir. No need to work on this.
> 
> 
> 
> If it's not used anymore, should we move it?

yeah we should actually delete the pos-dashboard package and remove it from the README

**Review by davidtaikocha — APPROVED** [review]

**Comment by xiaodino** [comment]
> > > As @cyberhorsey commented in the other PR,this package is not used anymore since Jolnir. No need to work on this.
> > 
> > 
> > If it's not used anymore, should we move it?
> 
> yeah we should actually delete the pos-dashboard package and remove it from the README

Removed

**Pull request closed without merging**
